# Generated by Django 5.1.1 on 2024-12-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruity', '0003_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.CharField(default='No description provided', max_length=300),
        ),
        migrations.AddField(
            model_name='recipe',
            name='imageUrl',
            field=models.CharField(default='https://img.freepik.com/premium-vector/cute-dizzy-lemon-character-funny-confused-lemon-fruit-cartoon-emoticon-flat-style_841552-205.jpg?w=1480', max_length=1000),
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_fat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_fiber',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_protein',
            field=models.FloatField(default=0),
        ),
    ]
