# Generated by Django 5.1.1 on 2024-12-13 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruity', '0004_recipe_description_recipe_imageurl_recipe_total_fat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='user',
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('imageUrl', models.CharField(default='https://img.freepik.com/premium-vector/cute-dizzy-lemon-character-funny-confused-lemon-fruit-cartoon-emoticon-flat-style_841552-205.jpg?w=1480', max_length=1000)),
                ('description', models.CharField(default='No description provided', max_length=300)),
                ('total_sugar', models.FloatField(default=0)),
                ('total_calories', models.FloatField(default=0)),
                ('total_fat', models.FloatField(default=0)),
                ('total_fiber', models.FloatField(default=0)),
                ('total_protein', models.FloatField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='fruity.category')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='fruity.recipes'),
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
