# Generated by Django 5.1.1 on 2024-12-14 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruity', '0006_ingredient_fat_ingredient_fiber_ingredient_protein_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='name',
            new_name='title',
        ),
    ]
