# Generated by Django 5.1.1 on 2024-12-14 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruity', '0007_rename_name_recipes_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='fruit_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fruit_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='description',
            field=models.CharField(default='No description provided', max_length=1000),
        ),
    ]
