# Generated by Django 5.1.1 on 2024-12-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruity', '0008_ingredient_fruit_owner_alter_recipes_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
